/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#221500',
                    50: '#f0f9ff',
                    100: '#e0f2fe',
                    200: '#bae6fd',
                    300: '#7dd3fc',
                    400: '#38bdf8',
                    500: '#0ea5e9',
                    600: '#0284c7',
                    700: '#0369a1',
                    800: '#075985',
                    900: '#0c4a6e',
                },
                "error": "#ba1a1a",
                "secondary-fixed-dim": "#a9c7ff",
                "surface-bright": "#f7f9fc",
                "inverse-on-surface": "#eff1f4",
                "primary-container": "#3d2800",
                "surface-tint": "#7f5700",
                "background": "#f7f9fc",
                "on-surface-variant": "#43474f",
                "on-tertiary-container": "#cd805d",
                "on-primary-fixed": "#281900",
                "surface-variant": "#e0e3e6",
                "on-primary-container": "#c38800",
                "on-error-container": "#93000a",
                "on-primary": "#ffffff",
                "on-secondary-container": "#315182",
                "on-error": "#ffffff",
                "tertiary-fixed": "#ffdbcd",
                "on-secondary-fixed-variant": "#264778",
                "surface-container": "#eceef1",
                "secondary": "#405f91",
                "secondary-fixed": "#d6e3ff",
                "on-tertiary-fixed-variant": "#713619",
                "primary-fixed-dim": "#ffba3c",
                "surface-container-high": "#e6e8eb",
                "surface": "#f7f9fc",
                "outline": "#747780",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#360f00",
                "tertiary": "#2f0c00",
                "secondary-container": "#a6c5fe",
                "tertiary-container": "#4f1c02",
                "inverse-primary": "#ffba3c",
                "primary-fixed": "#ffdead",
                "on-primary-fixed-variant": "#604100",
                "on-tertiary": "#ffffff",
                "outline-variant": "#c4c6d0",
                "inverse-surface": "#2d3133",
                "on-background": "#191c1e",
                "on-surface": "#191c1e",
                "tertiary-fixed-dim": "#ffb596",
                "surface-container-highest": "#e0e3e6",
                "surface-container-low": "#f2f4f7",
                "surface-dim": "#d8dadd",
                "on-secondary-fixed": "#001b3d",
                "on-secondary": "#ffffff"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "display": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
