"""create_all_tables

Revision ID: 67feaf3225ba
Revises: 
Create Date: 2026-05-19 13:20:04.773668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67feaf3225ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocos_logicos',
    sa.Column('bloco_id', sa.Integer(), nullable=False),
    sa.Column('nome_bloco', sa.String(length=255), nullable=False),
    sa.Column('descricao_bloco', sa.Text(), nullable=True),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bloco_id'),
    sa.UniqueConstraint('ordem_exibicao')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('foto_perfil', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pontos_norteadores',
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('bloco_id', sa.Integer(), nullable=False),
    sa.Column('nome_ponto', sa.String(length=255), nullable=False),
    sa.Column('pergunta_agente', sa.Text(), nullable=False),
    sa.Column('proposito_ponto', sa.Text(), nullable=False),
    sa.Column('instrucao_agente', sa.Text(), nullable=True),
    sa.Column('exemplo_resposta', sa.Text(), nullable=True),
    sa.Column('tipo_input', sa.Enum('TEXTO_LIVRE', 'LISTA_NUMERADA', 'SELECAO_UNICA', 'SELECAO_MULTIPLA', 'BOOLEANO', name='tipoinput'), nullable=False),
    sa.Column('opcoes_selecao', sa.JSON(), nullable=True),
    sa.Column('e_obrigatorio', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloco_id'], ['blocos_logicos.bloco_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ponto_id'),
    sa.UniqueConstraint('bloco_id', 'ordem_exibicao', name='uq_ponto_bloco_ordem')
    )
    op.create_table('projetos',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo_projeto', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_ultima_modificacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projeto_id')
    )
    op.create_table('contexto_projeto',
    sa.Column('contexto_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'RASCUNHO', 'RESPONDIDO', 'REVISADO', 'IGNORADO', name='statuscontexto'), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos_norteadores.ponto_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.projeto_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contexto_id'),
    sa.UniqueConstraint('projeto_id', 'ponto_id', name='uq_contexto_projeto_ponto')
    )
    op.create_table('historico_contexto',
    sa.Column('historico_id', sa.Integer(), nullable=False),
    sa.Column('contexto_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_anterior', sa.Text(), nullable=False),
    sa.Column('status_anterior', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'RASCUNHO', 'RESPONDIDO', 'REVISADO', 'IGNORADO', name='statuscontexto'), nullable=False),
    sa.Column('versao_anterior', sa.Integer(), nullable=False),
    sa.Column('data_substituicao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contexto_id'], ['contexto_projeto.contexto_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_contexto')
    op.drop_table('contexto_projeto')
    op.drop_table('projetos')
    op.drop_table('pontos_norteadores')
    op.drop_table('usuarios')
    op.drop_table('blocos_logicos')
    # ### end Alembic commands ###
